# Generated by Django 3.0.7 on 2020-06-06 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='pizzas',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='orders.Pizza'),
        ),
    ]
