# Generated by Django 3.0.7 on 2020-06-07 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200606_2216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='totalCost',
            new_name='Cost',
        ),
    ]
