# Generated by Django 3.0.7 on 2020-06-07 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_cartitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='Quantity',
            field=models.IntegerField(default=1),
        ),
    ]
